import type { RecordingEvent } from "@/lib/workspace/types";

export const recordingEvents: RecordingEvent[] = [
  // rec-1 — CRM export routine
  {
    id: "ev-1-01",
    recordingId: "rec-1",
    offsetMs: 0,
    type: "app_switch",
    fromApp: "Finder",
    toApp: "Salesforce",
  },
  {
    id: "ev-1-02",
    recordingId: "rec-1",
    offsetMs: 3200,
    type: "screenshot",
    appName: "Salesforce",
    windowTitle: "Accounts — All open deals",
    scene: "crm-list",
    caption: "Opened Accounts view filtered to Q2 pipeline.",
  },
  {
    id: "ev-1-03",
    recordingId: "rec-1",
    offsetMs: 8100,
    type: "click",
    appName: "Salesforce",
    target: "Export button",
  },
  {
    id: "ev-1-04",
    recordingId: "rec-1",
    offsetMs: 9400,
    type: "keystroke",
    appName: "Salesforce",
    text: "Q2 pipeline",
  },
  {
    id: "ev-1-05",
    recordingId: "rec-1",
    offsetMs: 14200,
    type: "shortcut",
    appName: "Salesforce",
    keys: "⌘A",
    action: "Select all rows",
  },
  {
    id: "ev-1-06",
    recordingId: "rec-1",
    offsetMs: 16800,
    type: "click",
    appName: "Salesforce",
    target: "Export CSV",
  },
  {
    id: "ev-1-07",
    recordingId: "rec-1",
    offsetMs: 19500,
    type: "screenshot",
    appName: "Salesforce",
    windowTitle: "Export options",
    scene: "crm-export-dialog",
    caption: "Confirmed CSV export with all columns.",
  },
  {
    id: "ev-1-08",
    recordingId: "rec-1",
    offsetMs: 22400,
    type: "app_switch",
    fromApp: "Salesforce",
    toApp: "Microsoft Excel",
  },
  {
    id: "ev-1-09",
    recordingId: "rec-1",
    offsetMs: 25800,
    type: "shortcut",
    appName: "Microsoft Excel",
    keys: "⌘V",
    action: "Paste export into sheet",
  },
  {
    id: "ev-1-10",
    recordingId: "rec-1",
    offsetMs: 31200,
    type: "screenshot",
    appName: "Microsoft Excel",
    windowTitle: "Q2_export_raw.xlsx",
    scene: "spreadsheet-raw",
    caption: "Pasted CRM export — duplicate columns visible.",
  },
  {
    id: "ev-1-11",
    recordingId: "rec-1",
    offsetMs: 45800,
    type: "shortcut",
    appName: "Microsoft Excel",
    keys: "⌘F",
    action: "Open find",
  },
  {
    id: "ev-1-12",
    recordingId: "rec-1",
    offsetMs: 52100,
    type: "keystroke",
    appName: "Microsoft Excel",
    text: "billing_id",
  },
  {
    id: "ev-1-13",
    recordingId: "rec-1",
    offsetMs: 62400,
    type: "scroll",
    appName: "Microsoft Excel",
    direction: "down",
  },
  {
    id: "ev-1-14",
    recordingId: "rec-1",
    offsetMs: 78500,
    type: "click",
    appName: "Microsoft Excel",
    target: "Delete column D",
  },
  {
    id: "ev-1-15",
    recordingId: "rec-1",
    offsetMs: 91200,
    type: "screenshot",
    appName: "Microsoft Excel",
    windowTitle: "Q2_export_clean.xlsx",
    scene: "spreadsheet-clean",
    caption: "Removed duplicate billing column; ready for ops review.",
  },

  // rec-2 — Invoice reconciliation
  {
    id: "ev-2-01",
    recordingId: "rec-2",
    offsetMs: 0,
    type: "app_switch",
    fromApp: "Slack",
    toApp: "Stripe Dashboard",
  },
  {
    id: "ev-2-02",
    recordingId: "rec-2",
    offsetMs: 4500,
    type: "screenshot",
    appName: "Stripe",
    windowTitle: "Payouts — May 2026",
    scene: "stripe-dashboard",
    caption: "Opened payouts view for current period.",
  },
  {
    id: "ev-2-03",
    recordingId: "rec-2",
    offsetMs: 12000,
    type: "click",
    appName: "Stripe",
    target: "Export payouts CSV",
  },
  {
    id: "ev-2-04",
    recordingId: "rec-2",
    offsetMs: 28000,
    type: "app_switch",
    fromApp: "Stripe Dashboard",
    toApp: "Microsoft Excel",
  },
  {
    id: "ev-2-05",
    recordingId: "rec-2",
    offsetMs: 35000,
    type: "screenshot",
    appName: "Microsoft Excel",
    windowTitle: "ledger_may.xlsx",
    scene: "spreadsheet-raw",
    caption: "Internal ledger open beside Stripe export.",
  },
  {
    id: "ev-2-06",
    recordingId: "rec-2",
    offsetMs: 52000,
    type: "shortcut",
    appName: "Microsoft Excel",
    keys: "⌘⇥",
    action: "Switch to Stripe export tab",
  },
  {
    id: "ev-2-07",
    recordingId: "rec-2",
    offsetMs: 68000,
    type: "keystroke",
    appName: "Microsoft Excel",
    text: "INV-2044",
  },
  {
    id: "ev-2-08",
    recordingId: "rec-2",
    offsetMs: 95000,
    type: "scroll",
    appName: "Microsoft Excel",
    direction: "down",
  },

  // rec-3 — Zendesk macro setup (short)
  {
    id: "ev-3-01",
    recordingId: "rec-3",
    offsetMs: 0,
    type: "screenshot",
    appName: "Zendesk",
    windowTitle: "Ticket #8842 — Billing inquiry",
    scene: "zendesk-ticket",
    caption: "Support ticket with customer context panel open.",
  },
  {
    id: "ev-3-02",
    recordingId: "rec-3",
    offsetMs: 8000,
    type: "shortcut",
    appName: "Zendesk",
    keys: "⌘K",
    action: "Open macro search",
  },
  {
    id: "ev-3-03",
    recordingId: "rec-3",
    offsetMs: 15000,
    type: "keystroke",
    appName: "Zendesk",
    text: "billing refund",
  },
  {
    id: "ev-3-04",
    recordingId: "rec-3",
    offsetMs: 22000,
    type: "click",
    appName: "Zendesk",
    target: "Apply macro: Billing — refund policy",
  },

  // rec-4 — Staging deploy
  {
    id: "ev-4-01",
    recordingId: "rec-4",
    offsetMs: 0,
    type: "app_switch",
    fromApp: "Terminal",
    toApp: "Google Chrome",
  },
  {
    id: "ev-4-02",
    recordingId: "rec-4",
    offsetMs: 5000,
    type: "screenshot",
    appName: "Terminal",
    windowTitle: "deploy-staging — zsh",
    scene: "terminal",
    caption: "Running staging deploy script.",
  },
  {
    id: "ev-4-03",
    recordingId: "rec-4",
    offsetMs: 45000,
    type: "shortcut",
    appName: "Google Chrome",
    keys: "⌘⇥",
    action: "Cycle browser tabs",
  },
  {
    id: "ev-4-04",
    recordingId: "rec-4",
    offsetMs: 62000,
    type: "screenshot",
    appName: "Google Chrome",
    windowTitle: "Staging — smoke tests",
    scene: "browser-tabs",
    caption: "Three staging tabs open for manual smoke checks.",
  },

  // rec-5 — Client intake
  {
    id: "ev-5-01",
    recordingId: "rec-5",
    offsetMs: 0,
    type: "screenshot",
    appName: "Google Chrome",
    windowTitle: "Client intake form",
    scene: "browser-tabs",
    caption: "Web intake form with empty required fields.",
  },
  {
    id: "ev-5-02",
    recordingId: "rec-5",
    offsetMs: 12000,
    type: "keystroke",
    appName: "Google Chrome",
    text: "Acme Corp · jordan@acme.io",
  },
  {
    id: "ev-5-03",
    recordingId: "rec-5",
    offsetMs: 28000,
    type: "app_switch",
    fromApp: "Google Chrome",
    toApp: "Salesforce",
  },
  {
    id: "ev-5-04",
    recordingId: "rec-5",
    offsetMs: 35000,
    type: "screenshot",
    appName: "Salesforce",
    windowTitle: "New account — Acme Corp",
    scene: "crm-list",
    caption: "Creating matching CRM record after form submit.",
  },
];

export function listRecordingEvents(recordingId: string): RecordingEvent[] {
  return recordingEvents
    .filter((event) => event.recordingId === recordingId)
    .sort((a, b) => a.offsetMs - b.offsetMs);
}

export function countRecordingEvents(recordingId: string): number {
  return recordingEvents.filter((event) => event.recordingId === recordingId)
    .length;
}
